version: '3.8'
services:

# NGINX Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./:/var/www"
      - "./docker-files/nginx/conf.d/:/etc/nginx/conf.d/"
 
