services:

# NGINX Service
  webserver:
    image: nginx:alpine
    container_name: aimoonhub-webserver
    restart: always
    tty: true
    ports:
      - "3001:3000"
    volumes:
      - "./:/var/www"
      - "./docker-files/nginx/conf.d/:/etc/nginx/conf.d/"
 
